IMAGE=docker.io/library/alpine@sha256:3e9b4b680bfc9fb5269227cffbd6d42be39fbf7c0b908123913864aa4447e764

CPU_LIMIT=0.5
MEMORY_LIMIT=256M
PIDS_LIMIT=64
TMPFS_SIZE=64m

NETWORK_MODE=none
READ_ONLY_ROOT=true
DROP_ALL_CAPABILITIES=true
NO_NEW_PRIVILEGES=true

RUN_AS_UID=1002
RUN_AS_GID=1002
USERNS_MODE=keep-id
